services:
  - type: web
    name: gwork-hr-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false  # Это означает, что значение нужно установить в панели управления
      - key: HH_API_TOKEN
        sync: false
      - key: SUPERJOB_API_KEY
        sync: false
      - key: YANDEX_LOGIN
        sync: false
      - key: YANDEX_APP_PASSWORD
        sync: false
